@baseUrl = http://localhost:3000

### Register user with JSON
POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "fougeray.florian+gayvent@gmail.com",
  "lastName": "Florian",
  "firstName": "Fougeray",
  "password": "AdmiN@123"
}
