@baseUrl = http://localhost:3000
@userId = xxxxx

### Delete user by id
DELETE {{baseUrl}}/users/{{userId}}

### Update user by id
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "firstName": "Updated",
  "lastName": "User",
  "email": "updated.user@example.com"
}
